algoritmo "calculo da idade"
// Função :
// Autor :
// Data : 22/04/2022
// Seção de Declarações 
var

   ano1: inteiro
   ano2: inteiro
   anos: inteiro
inicio

      Escreva("Em que ano estamos? ")
      Leia(ano1)
      Escreva("Em que ano eu nasci? ")
      Leia(ano2)
      anos<-ano1-ano2
      Escreval("Em", ano1, " você terá", anos, " anos.")
      Se(anos>=21)entao
           Escreval("E você já terá atingido a maioridade")
      fimse
fimalgoritmo
